// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiS7KJJs6ke8aUZepxap064J_Ykhr8ENE',
    appId: '1:499894610186:web:eb30e86edca662a0d9f2f3',
    messagingSenderId: '499894610186',
    projectId: 'agse-56638',
    authDomain: 'agse-56638.firebaseapp.com',
    storageBucket: 'agse-56638.appspot.com',
    measurementId: 'G-CM22P0NSP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyjegD_vedMnTkA5qFiilNQNxEVdSwR40',
    appId: '1:499894610186:android:33dc1b2fdc8a459fd9f2f3',
    messagingSenderId: '499894610186',
    projectId: 'agse-56638',
    storageBucket: 'agse-56638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVQKE0aa8RyXE7DT6vpoJJ24gEIBKO7N0',
    appId: '1:499894610186:ios:6d51d7ce7c30b786d9f2f3',
    messagingSenderId: '499894610186',
    projectId: 'agse-56638',
    storageBucket: 'agse-56638.appspot.com',
    iosBundleId: 'com.example.agse2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVQKE0aa8RyXE7DT6vpoJJ24gEIBKO7N0',
    appId: '1:499894610186:ios:6d51d7ce7c30b786d9f2f3',
    messagingSenderId: '499894610186',
    projectId: 'agse-56638',
    storageBucket: 'agse-56638.appspot.com',
    iosBundleId: 'com.example.agse2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiS7KJJs6ke8aUZepxap064J_Ykhr8ENE',
    appId: '1:499894610186:web:08c00ca85d677204d9f2f3',
    messagingSenderId: '499894610186',
    projectId: 'agse-56638',
    authDomain: 'agse-56638.firebaseapp.com',
    storageBucket: 'agse-56638.appspot.com',
    measurementId: 'G-7WSMYR02RF',
  );
}
